import re, sys

with open('src/App.jsx', 'r') as f:
    src = f.read()

# Safety check — abort if already patched
if 'GAME FILM' in src:
    print("ERROR: GAME FILM already exists in file. Patch already applied.")
    print("Run: git checkout HEAD~1 -- src/App.jsx   ...then re-run this script.")
    sys.exit(1)

# ── 1. Add GAME FILM to NAV ──────────────────────────────────
prog_match = re.search(r"\{[^}]*cat[^}]*'PROGRAM'[^}]*\}", src)
if not prog_match:
    print("ERROR: Could not find PROGRAM entry in NAV"); sys.exit(1)
insert_pos = prog_match.end()
line_end = src.find('\n', insert_pos)
new_entry = "\n  { cat:'GAME FILM', tabs:['vs Hobart','O Playlist','vs LJ','vs Merrillville'] },"
src = src[:line_end] + new_entry + src[line_end:]
print("✓ Step 1: Added GAME FILM to NAV")

# ── 2. Insert components before AccessGate ───────────────────
ANCHOR2 = 'function AccessGate('
if ANCHOR2 not in src:
    print("ERROR: AccessGate not found"); sys.exit(1)

COMPONENTS = r'''
// ── GAME FILM HELPERS ────────────────────────────────────────
const _heatClr = (v,mx)=>{const t=mx?Math.min(v/mx,1):0;const r=Math.round(0xFF+t*(0x0D-0xFF));const g=Math.round(0xF3+t*(0x1B-0xF3));const b=Math.round(0xC4+t*(0x2A-0xC4));return `rgb(${r},${g},${b})`}
const _heatTxt = (v,mx)=>(mx?Math.min(v/mx,1):0)>0.48?'#ffffff':'#1A2744'
const GameStatBox=({label,value,sub,color='#e3b341'})=>(<div style={{background:'#161b22',border:'1px solid #27313f',borderRadius:8,padding:'14px 10px',textAlign:'center',flex:1}}><div style={{fontSize:26,fontWeight:800,color,fontFamily:'Rajdhani,sans-serif',lineHeight:1}}>{value}</div><div style={{fontSize:9,fontWeight:700,color:'#8b949e',letterSpacing:1.5,marginTop:4,textTransform:'uppercase'}}>{label}</div>{sub&&<div style={{fontSize:8,color:'#69758a',marginTop:2}}>{sub}</div>}</div>)
const RunPassBar=({runs,passes,total})=>{const rP=Math.round(runs/total*100);const pP=100-rP;return(<div style={{marginBottom:14}}><div style={{display:'flex',justifyContent:'space-between',fontSize:9,color:'#8b949e',marginBottom:4}}><span style={{fontWeight:700,color:'#e3b341'}}>RUN {runs} ({rP}%)</span><span style={{fontWeight:700,color:'#06b6d4'}}>PASS {passes} ({pP}%)</span></div><div style={{display:'flex',height:20,borderRadius:4,overflow:'hidden'}}><div style={{width:`${rP}%`,background:'#1A2744',display:'flex',alignItems:'center',justifyContent:'center',fontSize:8,fontWeight:700,color:'#fff'}}>{rP}%</div><div style={{width:`${pP}%`,background:'#00695C',display:'flex',alignItems:'center',justifyContent:'center',fontSize:8,fontWeight:700,color:'#fff'}}>{pP}%</div></div></div>)}
const PZGrid=({data,mx,title})=>{const rows_=['SHORT (0-9)','INTER (10-19)','DEEP (20+)'];const cols_=['L','MID','R'];return(<div style={{marginBottom:16}}><div style={{fontSize:10,fontWeight:700,color:'#e3b341',letterSpacing:1.5,marginBottom:6}}>{title}</div><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={{width:'38%',padding:'4px 6px',background:'#1A2744',fontSize:8,color:'#8b949e',textAlign:'left'}}></th>{cols_.map(c=><th key={c} style={{padding:'4px 6px',background:'#1A2744',fontSize:9,fontWeight:700,color:'#fff',textAlign:'center'}}>{c}</th>)}</tr></thead><tbody>{data.map((row,i)=>(<tr key={i}><td style={{padding:'4px 6px',fontSize:8,fontWeight:700,color:'#8b949e',background:'#0f1419',borderBottom:'1px solid #1a212c'}}>{rows_[i]}</td>{row.map((v,j)=>{const bg=_heatClr(v,mx);const tc=_heatTxt(v,mx);return<td key={j} style={{padding:'6px',textAlign:'center',fontSize:12,fontWeight:800,color:tc,background:bg,borderBottom:'1px solid #1a212c',borderLeft:'1px solid #1a212c'}}>{v}</td>})}</tr>))}</tbody></table></div>)}
const GmPlayerRow=({name,num,pos,car,ryd,tgt,rec,cryd,expl})=>{const ypc=car?(ryd/car).toFixed(1):null;const ypr=rec?(cryd/rec).toFixed(1):null;const ct=tgt?Math.round(rec/tgt*100):null;const ypcC=ypc?(parseFloat(ypc)>=4.5?'#2fbf71':parseFloat(ypc)>=3.5?'#e5e7eb':'#ef4444'):'#8b949e';const ctC=ct?(ct>=70?'#2fbf71':ct>=55?'#e5e7eb':'#ef4444'):'#8b949e';return(<tr style={{borderBottom:'1px solid #1a212c'}}><td style={{padding:'6px 8px',fontSize:9,fontWeight:700,color:'#e5e7eb'}}>{name}</td><td style={{padding:'6px 4px',fontSize:8,color:'#8b949e',textAlign:'center'}}>#{num}</td><td style={{padding:'6px 4px',fontSize:8,color:'#8b949e',textAlign:'center'}}>{pos}</td>{car!==null&&<><td style={{padding:'6px 4px',fontSize:9,fontWeight:700,color:'#e3b341',textAlign:'center'}}>{car}</td><td style={{padding:'6px 4px',fontSize:9,fontWeight:700,color:'#e3b341',textAlign:'center'}}>{ryd}</td><td style={{padding:'6px 4px',fontSize:9,fontWeight:700,color:ypcC,textAlign:'center'}}>{ypc}</td></>}{tgt!==null&&<><td style={{padding:'6px 4px',fontSize:9,fontWeight:700,color:'#06b6d4',textAlign:'center'}}>{tgt}</td><td style={{padding:'6px 4px',fontSize:9,color:'#8b949e',textAlign:'center'}}>{rec}</td><td style={{padding:'6px 4px',fontSize:9,fontWeight:700,color:'#e3b341',textAlign:'center'}}>{cryd}</td><td style={{padding:'6px 4px',fontSize:9,color:'#e5e7eb',textAlign:'center'}}>{ypr||'...'}</td><td style={{padding:'6px 4px',fontSize:9,fontWeight:700,color:ctC,textAlign:'center'}}>{ct?ct+'%':'...'}</td><td style={{padding:'6px 4px',fontSize:9,fontWeight:700,color:expl>0?'#2fbf71':'#8b949e',textAlign:'center'}}>{expl>0?expl:'...'}</td></>}</tr>)}
const GmSec=({t,a='#e3b341'})=>(<div style={{background:'#0f1419',borderLeft:`3px solid ${a}`,padding:'5px 10px',marginBottom:8,marginTop:14}}><span style={{fontSize:9,fontWeight:800,color:a,letterSpacing:2}}>{t}</span></div>)
const RushTbl=({players})=>(<table style={{width:'100%',borderCollapse:'collapse',marginBottom:16}}><thead><tr style={{background:'#1A2744'}}>{['PLAYER','#','POS','CAR','YDS','YPC'].map(h=><th key={h} style={{padding:'5px 4px',fontSize:7.5,fontWeight:700,color:'#fff',textAlign:h==='PLAYER'?'left':'center',letterSpacing:.5}}>{h}</th>)}</tr></thead><tbody>{players.map((p,i)=><GmPlayerRow key={i} {...p} tgt={null} rec={null} cryd={null} expl={0}/>)}</tbody></table>)
const RecTbl=({players})=>(<table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr style={{background:'#1A2744'}}>{['PLAYER','#','POS','TGT','REC','YDS','YPR','C%','EXPL'].map(h=><th key={h} style={{padding:'5px 4px',fontSize:7.5,fontWeight:700,color:'#fff',textAlign:h==='PLAYER'?'left':'center',letterSpacing:.5}}>{h}</th>)}</tr></thead><tbody>{players.map((p,i)=><GmPlayerRow key={i} {...p} car={null} ryd={null}/>)}</tbody></table>)
const FPBars=({data})=>(<>{data.map(([z,v,mx,c])=>(<div key={z} style={{display:'flex',alignItems:'center',gap:8,marginBottom:5}}><div style={{width:80,fontSize:8,color:'#8b949e',flexShrink:0}}>{z}</div><div style={{flex:1,background:'#1a212c',borderRadius:3,height:14,position:'relative',overflow:'hidden'}}><div style={{position:'absolute',left:0,top:0,bottom:0,width:`${Math.round(v/mx*100)}%`,background:c+'55',borderRadius:3}}/></div><div style={{width:20,fontSize:9,fontWeight:700,color:c,textAlign:'right'}}>{v}</div></div>))}</>)
const DirBars=({data,total})=>(<>{data.map(([d,v])=>(<div key={d} style={{display:'flex',alignItems:'center',gap:8,marginBottom:6}}><div style={{width:90,fontSize:8,color:'#8b949e',flexShrink:0}}>{d}</div><div style={{flex:1,background:'#1a212c',borderRadius:3,height:16,position:'relative',overflow:'hidden'}}><div style={{position:'absolute',left:0,top:0,bottom:0,width:`${Math.round(v/total*100)}%`,background:'#1A2744',borderRadius:3}}/></div><div style={{width:24,fontSize:9,fontWeight:700,color:'#e3b341',textAlign:'right'}}>{v}</div></div>))}</>)
const FrontCards=({data})=>(<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:8}}>{data.map(([f,r,p,c])=>(<div key={f} style={{background:'#0f1419',border:`1px solid ${c}33`,borderRadius:6,padding:10}}><div style={{fontSize:9,fontWeight:700,color:c,marginBottom:4}}>{f}</div><div style={{fontSize:8,color:'#c9d1d9'}}>{r}</div><div style={{fontSize:8,color:'#8b949e'}}>{p}</div></div>))}</div>)

function HobartTab(){
  const rush=[{name:'Clevenger',num:'34',pos:'RB',car:10,ryd:38},{name:'Edmond',num:'31',pos:'RB',car:4,ryd:14},{name:'Noble',num:'28',pos:'RB',car:3,ryd:9},{name:'Dre',num:'20',pos:'WR',car:1,ryd:7},{name:'Novotney',num:'32',pos:'FB',car:1,ryd:4}]
  const recv=[{name:'Snow',num:'88',pos:'WR',tgt:5,rec:4,cryd:64,expl:1},{name:'McCray',num:'2',pos:'WR',tgt:5,rec:3,cryd:21,expl:0},{name:'Jay',num:'1',pos:'WR',tgt:4,rec:2,cryd:17,expl:0},{name:'Dauss',num:'6',pos:'WR',tgt:4,rec:2,cryd:13,expl:0},{name:'Dre',num:'20',pos:'WR',tgt:4,rec:3,cryd:23,expl:0},{name:'Baylor',num:'100',pos:'TE',tgt:3,rec:2,cryd:14,expl:0},{name:'Everts',num:'8',pos:'TE',tgt:4,rec:2,cryd:12,expl:0},{name:'Vollmer',num:'8s',pos:'WR',tgt:2,rec:1,cryd:6,expl:0}]
  return(<div style={{padding:20,maxWidth:900,margin:'0 auto'}}><div style={{marginBottom:16}}><div style={{fontSize:18,fontWeight:800,color:'#e3b341',fontFamily:'Rajdhani,sans-serif',letterSpacing:1}}>OFFENSE vs HOBART</div><div style={{fontSize:10,color:'#8b949e'}}>Scrimmage · Film analysis · Preseason 2026</div></div><div style={{display:'flex',gap:8,marginBottom:16,flexWrap:'wrap'}}><GameStatBox label="Total Plays" value="72"/><GameStatBox label="Run Plays" value="38" sub="53% of snaps"/><GameStatBox label="Pass Plays" value="34" sub="47% of snaps" color='#06b6d4'/><GameStatBox label="Explosive 20+ yds" value="4" sub="5.6% rate" color='#2fbf71'/><GameStatBox label="Red Zone Plays" value="6" sub="8.3% rate" color='#f97316'/></div><RunPassBar runs={38} passes={34} total={72}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}><div><PZGrid title="PASS ZONE TARGETS" data={[[3,3,4],[4,5,4],[3,6,2]]} mx={8}/><GmSec t="RUN DIRECTION"/><DirBars data={[['Run Left',10],['Run Middle',19],['Run Right',9]]} total={38}/><GmSec t="DEFENSIVE FRONT" a='#06b6d4'/><FrontCards data={[['4-Man Front','24 runs 94 yds 3.9 YPC','22 passes','#e3b341'],['3-Man Front','14 runs 48 yds 3.4 YPC','12 passes','#06b6d4']]}/><GmSec t="FIELD POSITION" a='#2fbf71'/><FPBars data={[['Own 1-20',4,28,'#ef4444'],['Own 21-39',14,28,'#e3b341'],['Mid 40s',28,28,'#06b6d4'],['Opp 21-39',20,28,'#2fbf71'],['Red Zone',6,28,'#f97316']]}/></div><div><GmSec t="RUSHING"/><RushTbl players={rush}/><GmSec t="RECEIVING" a='#06b6d4'/><RecTbl players={recv}/></div></div></div>)
}
function OPlaylistTab(){
  const rush=[{name:'Clevenger',num:'34',pos:'RB',car:11,ryd:68},{name:'Edmond',num:'31',pos:'RB',car:3,ryd:21},{name:'Dre',num:'20',pos:'WR',car:2,ryd:18},{name:'Noble',num:'28',pos:'RB',car:1,ryd:7},{name:'Novotney',num:'32',pos:'FB',car:1,ryd:4}]
  const recv=[{name:'Snow',num:'88',pos:'WR',tgt:10,rec:8,cryd:136,expl:4},{name:'Dre',num:'20',pos:'WR',tgt:7,rec:5,cryd:46,expl:2},{name:'McCray',num:'2',pos:'WR',tgt:7,rec:6,cryd:44,expl:2},{name:'Jay',num:'1',pos:'WR',tgt:5,rec:3,cryd:29,expl:1},{name:'Baylor',num:'100',pos:'TE',tgt:4,rec:2,cryd:17,expl:0},{name:'Dauss',num:'6',pos:'WR',tgt:4,rec:3,cryd:19,expl:0},{name:'Everts',num:'8',pos:'TE',tgt:3,rec:2,cryd:15,expl:0}]
  return(<div style={{padding:20,maxWidth:900,margin:'0 auto'}}><div style={{marginBottom:12}}><div style={{fontSize:18,fontWeight:800,color:'#e3b341',fontFamily:'Rajdhani,sans-serif',letterSpacing:1}}>O PLAYLIST</div><div style={{fontSize:10,color:'#8b949e'}}>Highlights Reel · Film analysis · Preseason 2026</div></div><div style={{background:'#0a1a10',border:'1px solid #2fbf71',borderRadius:6,padding:'6px 12px',marginBottom:14,display:'inline-block'}}><span style={{fontSize:9,fontWeight:700,color:'#2fbf71'}}>BEST SESSION - 12 Explosive Plays (16.9%)</span></div><div style={{display:'flex',gap:8,marginBottom:16,flexWrap:'wrap'}}><GameStatBox label="Total Plays" value="71"/><GameStatBox label="Run Plays" value="31" sub="44% of snaps"/><GameStatBox label="Pass Plays" value="40" sub="56% of snaps" color='#06b6d4'/><GameStatBox label="Explosive 20+ yds" value="12" sub="Best session" color='#2fbf71'/><GameStatBox label="Red Zone Plays" value="13" sub="18.3% rate" color='#f97316'/></div><RunPassBar runs={31} passes={40} total={71}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}><div><PZGrid title="PASS ZONE TARGETS" data={[[3,4,4],[4,5,4],[4,8,4]]} mx={8}/><GmSec t="RUN DIRECTION"/><DirBars data={[['Run Left',9],['Run Middle',15],['Run Right',7]]} total={31}/><GmSec t="DEFENSIVE FRONT" a='#06b6d4'/><FrontCards data={[['4-Man Front','18 runs 124 yds 6.9 YPC','26 passes','#e3b341'],['3-Man Front','13 runs 52 yds 4.0 YPC','14 passes','#06b6d4']]}/><GmSec t="FIELD POSITION" a='#2fbf71'/><FPBars data={[['Own 1-20',2,28,'#ef4444'],['Own 21-39',8,28,'#e3b341'],['Mid 40s',20,28,'#06b6d4'],['Opp 21-39',28,28,'#2fbf71'],['Red Zone',13,28,'#f97316']]}/></div><div><GmSec t="RUSHING"/><RushTbl players={rush}/><GmSec t="RECEIVING" a='#06b6d4'/><RecTbl players={recv}/></div></div></div>)
}
function LJTab(){
  const rush=[{name:'Clevenger',num:'34',pos:'RB',car:12,ryd:44},{name:'Edmond',num:'31',pos:'RB',car:4,ryd:16},{name:'Dre',num:'20',pos:'WR',car:3,ryd:15},{name:'Noble',num:'28',pos:'RB',car:2,ryd:8},{name:'Novotney',num:'32',pos:'FB',car:1,ryd:4}]
  const recv=[{name:'Snow',num:'88',pos:'WR',tgt:6,rec:5,cryd:74,expl:2},{name:'McCray',num:'2',pos:'WR',tgt:7,rec:5,cryd:34,expl:1},{name:'Dre',num:'20',pos:'WR',tgt:7,rec:5,cryd:38,expl:1},{name:'Jay',num:'1',pos:'WR',tgt:5,rec:3,cryd:22,expl:0},{name:'Dauss',num:'6',pos:'WR',tgt:5,rec:3,cryd:19,expl:0},{name:'Everts',num:'8',pos:'TE',tgt:5,rec:3,cryd:17,expl:0},{name:'Baylor',num:'100',pos:'TE',tgt:4,rec:2,cryd:14,expl:0},{name:'Vollmer',num:'8s',pos:'WR',tgt:2,rec:1,cryd:8,expl:0}]
  return(<div style={{padding:20,maxWidth:900,margin:'0 auto'}}><div style={{marginBottom:12}}><div style={{fontSize:18,fontWeight:800,color:'#e3b341',fontFamily:'Rajdhani,sans-serif',letterSpacing:1}}>OFFENSE vs LJ</div><div style={{fontSize:10,color:'#8b949e'}}>Scrimmage · Film analysis · Preseason 2026</div></div><div style={{background:'#1a0a00',border:'1px solid #f97316',borderRadius:6,padding:'6px 12px',marginBottom:14,display:'inline-block'}}><span style={{fontSize:9,fontWeight:700,color:'#f97316'}}>MOST 3-MAN FRONTS - YPC dips vs 3-Man sets</span></div><div style={{display:'flex',gap:8,marginBottom:16,flexWrap:'wrap'}}><GameStatBox label="Total Plays" value="89" sub="Largest sample"/><GameStatBox label="Run Plays" value="47" sub="53% of snaps"/><GameStatBox label="Pass Plays" value="42" sub="47% of snaps" color='#06b6d4'/><GameStatBox label="Explosive 20+ yds" value="6" sub="6.7% rate" color='#2fbf71'/><GameStatBox label="Red Zone Plays" value="8" sub="9.0% rate" color='#f97316'/></div><RunPassBar runs={47} passes={42} total={89}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}><div><PZGrid title="PASS ZONE TARGETS" data={[[5,3,5],[4,6,4],[4,7,4]]} mx={8}/><GmSec t="RUN DIRECTION"/><DirBars data={[['Run Left',14],['Run Middle',22],['Run Right',11]]} total={47}/><GmSec t="DEFENSIVE FRONT" a='#06b6d4'/><FrontCards data={[['4-Man Front','28 runs 102 yds 3.6 YPC','24 passes','#e3b341'],['3-Man Front','19 runs 64 yds 3.4 YPC','23 passes','#06b6d4']]}/><GmSec t="FIELD POSITION" a='#2fbf71'/><FPBars data={[['Own 1-20',5,32,'#ef4444'],['Own 21-39',18,32,'#e3b341'],['Mid 40s',32,32,'#06b6d4'],['Opp 21-39',26,32,'#2fbf71'],['Red Zone',8,32,'#f97316']]}/></div><div><GmSec t="RUSHING"/><RushTbl players={rush}/><GmSec t="RECEIVING" a='#06b6d4'/><RecTbl players={recv}/></div></div></div>)
}
function MerrillvilleTab(){
  return(<div style={{padding:20,maxWidth:900,margin:'0 auto'}}><div style={{marginBottom:20}}><div style={{fontSize:18,fontWeight:800,color:'#e3b341',fontFamily:'Rajdhani,sans-serif',letterSpacing:1}}>OFFENSE vs MERRILLVILLE</div><div style={{fontSize:10,color:'#8b949e'}}>Film analysis · Preseason 2026</div></div><div style={{background:'#161b22',border:'1px solid #27313f',borderRadius:12,padding:40,textAlign:'center'}}><div style={{fontSize:36,marginBottom:12}}>Film Pending</div><div style={{fontSize:14,fontWeight:700,color:'#e5e7eb',marginBottom:8}}>Film Analysis Pending</div><div style={{fontSize:11,color:'#8b949e',maxWidth:360,margin:'0 auto',lineHeight:1.6}}>The Merrillville footage has not been charted yet. Stats and player breakdowns will appear here once film review is complete.</div><div style={{marginTop:24,display:'flex',justifyContent:'center',gap:12,flexWrap:'wrap'}}>{['Total Plays','Run %','Pass %','Explosive','YPC','Comp %'].map(s=>(<div key={s} style={{background:'#0d1117',border:'1px solid #27313f',borderRadius:6,padding:'8px 14px',minWidth:90}}><div style={{fontSize:18,fontWeight:800,color:'#374151',fontFamily:'Rajdhani,sans-serif'}}>-</div><div style={{fontSize:7,color:'#4b5563',letterSpacing:1,textTransform:'uppercase',marginTop:2}}>{s}</div></div>))}</div></div></div>)
}

'''

src = src.replace(ANCHOR2, COMPONENTS + ANCHOR2, 1)
print("✓ Step 2: Inserted 4 game film tab components")

# ── 3. Add render cases after AI Coach ───────────────────────
ANCHOR3 = "tab==='AI Coach'"
if ANCHOR3 not in src:
    print("ERROR: Could not find AI Coach render case"); sys.exit(1)
idx = src.index(ANCHOR3)
line_end = src.find('\n', idx)
NEW_CASES = "\n              {tab==='vs Hobart' && <HobartTab/>}\n              {tab==='O Playlist' && <OPlaylistTab/>}\n              {tab==='vs LJ' && <LJTab/>}\n              {tab==='vs Merrillville' && <MerrillvilleTab/>}"
src = src[:line_end] + NEW_CASES + src[line_end:]
print("✓ Step 3: Added render cases")

with open('src/App.jsx', 'w') as f:
    f.write(src)

print("\n✅ All done — run: git add . && git commit -m 'Add GAME FILM tabs' && git push")
